name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mongodb

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: |
          composer test
